version: "3.9"
services:
  java8-notification-server:
    build: ./java8
    ports:
      - 7000:7000
    depends_on:
      - mock-java8-notification-sender
    environment:
      server.sleepTime: 200
      notification.sender-server.java8.url: "http://mock-java8-notification-sender:7004/send/"
      notification.sender-server.golang.url: "http://mock-golang-notification-sender:7005/send/"
    networks:
      - notification_bridge

  java19-notification-server:
    build: ./java19
    ports:
      - 7001:7001
    depends_on:
      - mock-java8-notification-sender
    environment:
      server.sleepTime: 200
      notification.sender-server.java8.url: "http://mock-java8-notification-sender:7004/send/"
      notification.sender-server.golang.url: "http://mock-golang-notification-sender:7005/send/"
    networks:
      - notification_bridge

  golang-notification-server:
    build: ./golang
    ports:
      - 7002:7002
    depends_on:
      - mock-java8-notification-sender
      - mock-golang-notification-sender
    environment:
      server.sleepTime: 200
      notification.sender-server.java8.url: "http://mock-java8-notification-sender:7004/send/"
      notification.sender-server.golang.url: "http://mock-golang-notification-sender:7005/send/"
    networks:
      - notification_bridge

  python-notification-server:
    build: ./python
    ports:
      - 7003:7003
    depends_on:
      - mock-java8-notification-sender
      - mock-golang-notification-sender
    environment:
      server.sleepTime: 200
      notification.sender-server.java8.url: "http://mock-java8-notification-sender:7004/send/"
      notification.sender-server.golang.url: "http://mock-golang-notification-sender:7005/send/"
    networks:
      - notification_bridge

  mock-java8-notification-sender:
    build: ./mock-java8-notification-sender
    ports:
      - 7004:7004
    environment:
      server.port: 7004
    networks:
      - notification_bridge

  mock-golang-notification-sender:
    build: ./mock-golang-notification-sender
    ports:
      - 7005:7005
    environment:
      server.port: 7005
    networks:
      - notification_bridge

networks:
  notification_bridge:
    driver: bridge
